Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import imageryclient as ic
from caveclient import CAVEclient

client = CAVEclient('minnie65_public', auth_token=os.environ['API_SECRET'])

img_client = ic.ImageryClient(client=client)

ctr = [240640, 207872, 21360]

image, segs = img_client.image_and_segmentation_cutout(ctr,
                                                       split_segmentations=True,
                                                       bbox_size=(512, 512),
                                                       scale_to_bounds=True,
)

ic.composite_overlay(segs, imagery=image, palette='husl').convert("RGB")
# Note: the final `.convert('RGB')` is needed to build this documetnation, but is not required to run locally.
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mimageryclient[39;00m [38;5;28;01mas[39;00m [38;5;21;01mic[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcaveclient[39;00m [38;5;28;01mimport[39;00m CAVEclient
[0;32m----> 4[0m client [38;5;241m=[39m CAVEclient([38;5;124m'[39m[38;5;124mminnie65_public[39m[38;5;124m'[39m, auth_token[38;5;241m=[39m[43mos[49m[38;5;241m.[39menviron[[38;5;124m'[39m[38;5;124mAPI_SECRET[39m[38;5;124m'[39m])
[1;32m      6[0m img_client [38;5;241m=[39m ic[38;5;241m.[39mImageryClient(client[38;5;241m=[39mclient)
[1;32m      8[0m ctr [38;5;241m=[39m [[38;5;241m240640[39m, [38;5;241m207872[39m, [38;5;241m21360[39m]

[0;31mNameError[0m: name 'os' is not defined

